deploy:
  runs-on: windows-latest   # ✅ instead of ubuntu-latest
  needs: build
  environment:
    name: 'Production'
    url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
      
  steps:
  - name: Download artifact from build job
    uses: actions/download-artifact@v3
    with:
      name: python-app
      path: .

  - name: Create startup script
    run: |
      echo @echo off > startup.bat
      echo set PYTHONUNBUFFERED=1 >> startup.bat
      echo set PYTHONDONTWRITEBYTECODE=1 >> startup.bat
      echo set PYTHONOPTIMIZE=2 >> startup.bat
      echo python -m gunicorn --bind 0.0.0.0:%PORT% --workers 2 main:app >> startup.bat

  - name: Create web.config for Azure
    run: |
      echo ^<?xml version="1.0" encoding="utf-8"?^> > web.config
      echo ^<configuration^> >> web.config
      echo   ^<system.webServer^> >> web.config
      echo     ^<handlers^> >> web.config
      echo       ^<add name="PythonHandler" path="*" verb="*" modules="httpPlatformHandler" resourceType="Unspecified"/^> >> web.config
      echo     ^</handlers^> >> web.config
      echo     ^<httpPlatform processPath="D:\home\Python311\python.exe" arguments="-m gunicorn --bind 0.0.0.0:%%HTTP_PLATFORM_PORT%% --workers 2 --timeout 120 main:app" stdoutLogEnabled="true" stdoutLogFile="D:\home\LogFiles\python.log" startupTimeLimit="60" requestTimeout="00:04:00"^> >> web.config
      echo       ^<environmentVariables^> >> web.config
      echo         ^<environmentVariable name="PYTHONUNBUFFERED" value="1" /^> >> web.config
      echo         ^<environmentVariable name="PYTHONDONTWRITEBYTECODE" value="1" /^> >> web.config
      echo         ^<environmentVariable name="PYTHONOPTIMIZE" value="2" /^> >> web.config
      echo       ^</environmentVariables^> >> web.config
      echo     ^</httpPlatform^> >> web.config
      echo   ^</system.webServer^> >> web.config
      echo ^</configuration^> >> web.config

  - name: Deploy to Azure Web App
    id: deploy-to-webapp
    uses: azure/webapps-deploy@v2
    with:
      app-name: ${{ env.AZURE_WEBAPP_NAME }}
      publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
      package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

  - name: Verify deployment
    run: |
      echo "Deployment completed. Checking application health..."
      curl -s -o nul -w "HTTP Status: %{http_code}" https://${{ env.AZURE_WEBAPP_NAME }}.azurewebsites.net/healthz
